apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/mtr-operator.mtr: ""
  name: mtr-operator
  namespace: mtr
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: mtr-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mtr-operator.1.0.2