apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: sample-keda-app
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: thanos-token-9dfxx       # update this
    key: token
  - parameter: ca
    name: thanos-token-9dfxx       # update this
    key: ca.crt