kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-argocd-application-controller-additonal
  labels:
    app.kubernetes.io/instance: openshift-gitops
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - "integreatly.org"
    resources:
      - grafanadatasources
  - verbs:
      - '*'
    apiGroups:
      - "integreatly.org"
    resources:
      - grafanas
  - verbs:
      - '*'
    apiGroups:
      - "batch"
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - "logging.openshift.io"
    resources:
      - elasticsearches
      - clusterloggings
  - verbs:
      - '*'
    apiGroups:
      - "redhatcop.redhat.io"
    resources:
      - namespaceconfigs
  - verbs:
      - '*'
    apiGroups:
      - "project.openshift.io"
    resources:
      - projects
  - verbs:
      - '*'
    apiGroups:
      - "imageregistry.operator.openshift.io"
    resources:
      - configs
  - verbs:
      - '*'
    apiGroups:
      - "machineconfiguration.openshift.io"
    resources:
      - machineconfigpools
  - verbs:
      - '*'
    apiGroups:
      - "machineconfiguration.openshift.io"
    resources:
      - machineconfigs
  - verbs:
      - '*'
    apiGroups:
      - "security.openshift.io"
    resources:
      - securitycontextconstraints
  - verbs:
      - '*'
    apiGroups:
      - "oauth.openshift.io"
    resources:
      - oauthclients
  - verbs:
      - '*'
    apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - resourcequotas
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - services
  - verbs:
      - '*'
    apiGroups:
      - "apps"
    resources:
      - deployments
  - verbs:
      - '*'
    apiGroups:
      - "apps"
    resources:
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
  - verbs:
      - '*'
    apiGroups:
      - "route.openshift.io"
    resources:
      - routes
  - verbs:
      - '*'
    apiGroups:
      - "build.openshift.io"
    resources:
      - buildconfigs
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - "nodes"
  - verbs:
      - '*'
    apiGroups:
      - "tackle.konveyor.io"
    resources:
      - "tackles"
  - verbs:
      - '*'
    apiGroups:
      - "windup.jboss.org"
    resources:
      - "windups"
  - verbs:
      - '*'
    apiGroups:
      - "operator.cryostat.io"
    resources:
      - "cryostats"
  - verbs:
      - '*'
    apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "servicemonitors"
  - verbs:
      - '*'
    apiGroups:
      - "keda.sh"
    resources:
      - "triggerauthentications"
      - "scaledobjects"


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-additonal-rbac
  labels:
    app.kubernetes.io/instance: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-argocd-application-controller-additonal