apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration-toolkit-for-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-apac-stp/java-troubleshooting-tuning.git
    targetRevision: main
    path: GitOps/applications/mta
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  destination: 
    name: in-cluster