apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-for-apps-kustomize
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/redhat-apac-stp/java-troubleshooting-tuning.git'
    path: GitOps/overlays/rajiv-ranjan
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
