apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "App for Apps"
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-apac-stp/java-troubleshooting-tuning.git
    targetRevision: main
    path: GitOps/argocd-applications
  syncPolicy:
    automated: {}
  destination: 
    name: in-cluster