apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration-toolkit-for-runtime
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-apac-stp/java-troubleshooting-tuning.git
    targetRevision: main
    path: GitOps/applications/mtr
  syncPolicy:
    automated: {}
    # syncOptions:
    # - CreateNamespace=true
  destination: 
    name: in-cluster